---
- hosts: ubuntu
  become: yes
  become_user: root

  vars:
    - username: masaki
    - password: passw0rd

  tasks:
  - name: set timezone to Asia/Tokyo
    timezone:
      name: Asia/Tokyo

  - name: install desktop
    apt:
      name:
        - ubuntu-desktop
        - ibus-mozc

  - name: install packages for japanese
    shell: "apt install -y $(check-language-support -l ja)"
    changed_when: no

  - name: install tools
    apt:
      name:
        - vim
        - tmux
        - zsh
        - zplug
        - golang
        - fzf
        - peco
        - docker.io
        - docker-compose

  - name: change directory mode
    file:
      path: /usr/share/zplug
      state: directory
      mode: '0775'

  - name: modify sshd config
    replace:
      path: /etc/ssh/sshd_config
      regexp: "^PasswordAuthentication no"
      replace: "PasswordAuthentication yes"

  - name: add user
    user:
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512') }}"
      shell: /usr/bin/zsh
      groups: root,sudo,docker
      update_password: on_create
      generate_ssh_key: yes
      ssh_key_file: .ssh/id_rsa

  - name: add ssh config
    template:
      src: ./ssh-config.j2
      dest: "/home/{{ username }}/.ssh/config"
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: 0600


